// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ViagensApi.Data;

#nullable disable

namespace ApiGerenciadorDeViagens.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiGerenciadorDeViagens.Modelos.Modelo_Passagens", b =>
                {
                    b.Property<Guid>("NumeroPassagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Companhia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataIda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataVolta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaDePagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraIda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraVolta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("assentos")
                        .HasColumnType("integer");

                    b.HasKey("NumeroPassagem");

                    b.HasIndex("UsuarioCPF");

                    b.ToTable("Tabela_Passagem");
                });

            modelBuilder.Entity("ViagensApi.Modelos.Modelo_Usuario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco_Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco_Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco_Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone_Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone_Fixo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CPF");

                    b.ToTable("Tabela_Usuario");
                });

            modelBuilder.Entity("ViagensApi.Modelos.Modelo_Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cadeiras")
                        .HasColumnType("integer");

                    b.Property<int>("CadeirasOcupadas")
                        .HasColumnType("integer");

                    b.Property<string>("Companhia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("Modelo_PassagensNumeroPassagem")
                        .HasColumnType("uuid");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Precos")
                        .HasColumnType("double precision");

                    b.Property<string>("dataIda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dataVolta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horaIda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("horaVolta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Modelo_PassagensNumeroPassagem");

                    b.ToTable("Tabela_Viagem");
                });

            modelBuilder.Entity("ApiGerenciadorDeViagens.Modelos.Modelo_Passagens", b =>
                {
                    b.HasOne("ViagensApi.Modelos.Modelo_Usuario", "Usuario")
                        .WithMany("Passagem")
                        .HasForeignKey("UsuarioCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ViagensApi.Modelos.Modelo_Viagem", b =>
                {
                    b.HasOne("ApiGerenciadorDeViagens.Modelos.Modelo_Passagens", null)
                        .WithMany("Viagens")
                        .HasForeignKey("Modelo_PassagensNumeroPassagem");
                });

            modelBuilder.Entity("ApiGerenciadorDeViagens.Modelos.Modelo_Passagens", b =>
                {
                    b.Navigation("Viagens");
                });

            modelBuilder.Entity("ViagensApi.Modelos.Modelo_Usuario", b =>
                {
                    b.Navigation("Passagem");
                });
#pragma warning restore 612, 618
        }
    }
}
